# Generated by Django 3.2.12 on 2022-04-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True, default='')),
                ('author', models.CharField(blank=True, max_length=100)),
                ('link', models.URLField(blank=True, default='')),
                ('public', models.BooleanField(default=True)),
                ('contentType', models.CharField(choices=[('article', 'article'), ('book', 'book'), ('music', 'music'), ('video', 'video'), ('podcast', 'podcast'), ('text', 'text'), ('meme', 'meme')], default='text', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('displayPath', models.CharField(default='', max_length=40)),
                ('subtitle', models.CharField(blank=True, max_length=512)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('content', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField(default=False)),
                ('isMarkdownContent', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(to='blog.Tag')),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
