# Generated by Django 3.2.12 on 2022-02-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180612_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isMarkdownContent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
