# Generated by Django 3.2.20 on 2023-11-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='contentType',
            field=models.CharField(choices=[('article', 'article'), ('book', 'book'), ('music', 'music'), ('video', 'video'), ('podcast', 'podcast'), ('text', 'text'), ('meme', 'meme'), ('site', 'site')], default='text', max_length=10),
        ),
    ]
