# Generated by Django 3.2.12 on 2022-03-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_tag_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True, default='')),
                ('author', models.CharField(blank=True, max_length=100)),
                ('link', models.URLField(blank=True, default='')),
                ('contentType', models.CharField(choices=[('article', 'article'), ('music', 'music'), ('video', 'video'), ('podcast', 'podcast'), ('text', 'text')], default='text', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
