# Generated by Django 3.2.12 on 2022-03-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='extra',
            name='contentType',
            field=models.CharField(choices=[('article', 'article'), ('book', 'book'), ('music', 'music'), ('video', 'video'), ('podcast', 'podcast'), ('text', 'text')], default='text', max_length=10),
        ),
    ]
